@BaseUrl= http://127.1.1:3000
@AuthToken= {{authenticate.response.body.accessToken}}
# MESSAGE
### List all messages
GET {{BaseUrl}}/message/
?limit=2
&offset=2

### List one message
GET {{BaseUrl}}/message/2

### Create a message
POST  {{BaseUrl}}/message/
Content-Type: application/json
Authorization: Bearer dshdwjkjeijrijkfhusfjsa.fhfnjfjijfdij.iojfijfjefsjmiokfjeisa

{
    "text": "Morning",
    "ofId": 4,
    "toId":5
}

### Update a message
PATCH  {{BaseUrl}}/message/4
Content-Type: application/json

{
    "text": "Hi !!!"
}

### Delete one message by id
DELETE {{BaseUrl}}/message/3


# PEOPLE


### List all people
GET {{BaseUrl}}/people
Authorization: Bearer {{AuthToken}}

### List one person
GET {{BaseUrl}}/people/8
Authorization: Bearer {{AuthToken}}
### Create a person
POST  {{BaseUrl}}/people/
Content-Type: application/json

{
    "name": "josuel5",
    "email": "test5@test.com",
    "password":"12345"
}

### Update a person
PATCH  {{BaseUrl}}/people/4
Content-Type: application/json
Authorization: Bearer {{AuthToken}}

{
    "name": "John Doe"
}

### Delete one person by id
DELETE {{BaseUrl}}/people/2
Authorization: Bearer {{AuthToken}}


# AUTH



### Login person
# @name authenticate
POST  {{BaseUrl}}/auth/
Content-Type: application/json

{
    "email": "test@test.com",
    "password":"12345"
}
